# Used when a release is pushed to GitHub
# This does not make use of any caching as to ensure a clean build
# Credits to https://github.com/CaffeineMC/sodium/blob/dc7dc4c634316ac8b510d2dc8290079ebc462778/.github/workflows/build-release.yml
name: build-release

# todo: execute on git tag with name v{version number}
# todo: publish to modrinth and curseforge
# https://github.com/Kira-NT/mc-publish
# https://wiki.fabricmc.net/tutorial:publishing_mods_using_github_actions
on:
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v3

      - name: Setup JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-read-only: true

      - name: Build with Gradle
        run: ./gradlew build
